### ISSUE TITLE
Embedded collision Issue continued

### ISSUE THREAD

**Issue by Denis-3D** [Skylumz/Sollumz#299]
Issue: Objects with (Bound Composite with Bound primitives) do not work properly in-game

Software:

- Blender 3.1
- Sollumz GitHub version downloaded today (28.03.2022)
- CodeWalker v42

Still using the same two objects for testing:
1. tr_prop_tr_door2 with Bound Geometry and Bound Poly Mesh 
This one seems to work properly since the last update, but any other type of Bounds is not for example added 'Bound Poly Box' and this box only works with Ped Weapon & Camera clips
![image](https://user-images.githubusercontent.com/7430830/160375530-47ac1d85-e4c3-4809-8296-baf7de1054a3.png)

2. tr_prop_tr_iaa_base_door_01a with Bound Composite with Bound Boxes inside. 
This one is still fully bugged, Ped interacts but the camera & weapon still clip through.

At this point, I feel like only Bound Poly Mesh works fine and without any problems, the rest of the options always have some problems.

None of the above applies to YBNs, already edited multiple ones and only Embedded cols give me headaches.

**Comment by CFox04** [comment]
Hm, if I convert it to a Bound GeometryBVH instead of Bound Geometry the collision works fine. I also changed the collision material from default to something else which caused the bullet holes to show up. 
![image](https://user-images.githubusercontent.com/46362482/160401029-ffeebdd8-6fcf-4b29-be33-72c9602577ee.png)
I guess just do this for now while I find a fix. Maybe Bound Geometry doesn't work with poly boxes? I thought I have seen some that do. You can change the type like this: https://gyazo.com/0e047270977a27205bb489f7e40a5d92.mp4

**Comment by Denis-3D** [comment]
Ill check 👌

**Comment by CFox04** [comment]
Hm just ran a python script on all ybns and yfts and found no occurrences of Bound Poly Box, Sphere, Cylinder, or Capsule in any of the files. I guess those types only work in a Bound GeometryBVH. We will have to make sure the user doesn't export with those types inside a Bound Geometry then.

**Comment by CFox04** [comment]
I just pushed a commit that ignores those types on export when parented to a Bound Geometry. I'll also add a warning message, but need to refactor something first before that's possible.

I tried adding a Bound Box to Bound Geometry instead and it worked fine. If you have any more issues feel free to post again.
