### ISSUE TITLE
Texture import issue in latest version

### ISSUE THREAD

**Issue by d1n3301** [Skylumz/Sollumz#303]
A bug in the new version with the import of textures, on the previous one everything was fine with the import

Blender 3.1.2
Sollumz GitHub version downloaded today (06.04.2022)
CodeWalker v42

https://streamable.com/90h5bp

**Comment by Hancapo** [comment]
![image](https://user-images.githubusercontent.com/20731612/162089312-dd91c785-38bc-4671-af86-161e18cf09b8.png)
I can't replicate the Issue, I'm using the exact same version you are using.
Try again with a fresh xml file from CodeWalker.

**Comment by ffzero58** [comment]
Replicated on Blender 3.0 + Sollumz version 4144ecc

Reverting to 54d5146 resolved the issue.

**Comment by Hancapo** [comment]
I just tested this on another PC that never had any Blender installation before and I still can't replicate the issue, it must be something else.

**Comment by Hancapo** [comment]
Upon further investigation, the current behavior of the shared textures folder (which can be set in Sollumz' settings) breaks the model importing if used, as @CFox04 stated in #discussion, in order to load non-embedded textures you have to use `Find Missing Files` option, you have to avoid using this option to avoid any issue.
![image](https://user-images.githubusercontent.com/20731612/162112405-a4cea4b9-0c3d-4627-a621-5a2f5f777cae.png)

**Comment by CFox04** [comment]
#305
