### ISSUE TITLE
Export issues with map YBN

### ISSUE THREAD

**Issue by PichotM** [Skylumz/Sollumz#316]
Hello, so I tried to simply import and export a ybn of the game. The import/export of the XML works fine in the addons but it ends up breaking the collision after the export if you try to open it / test it the collisions will not be working at all.

Steps to reproduce:
- Export YBN of the game like `hei_po1_sh2_0.ybn` to its XML format with CodeWalker
- Import the XML into Blender
- Export the XML into the XML format using the plugin
- Import it to CodeWalker, open it
- Collisions will be missing and not working

**Comment by Ekinoxx0** [comment]
Hi, I tried to reproduce your problem with success :/
I've heard of similar issues with some collegues (exporting is empty) but they fixed it since then.

Just to be sure :
 - I exported to XML
 - Imported to Blender (Every collision is visible)
 - Exported from Blender with valid options checked (Sollum Types Bounds is SELECTED)
 - Imported into CodeWalker (Every collision is visible, materials seems valid)
 - Launched a FiveM server with the collision streamed, the collision works
 
I could be missing a step or something particular in your setup is affecting this export process (like we saw with weird path names)

Can you describe with more details what is missing or not working from your exported collision ?

**Comment by Hancapo** [comment]
I also tried to reproduce your problem, I don't have this issue, didn't test it in FiveM. 
it must be something in your end.

![image](https://user-images.githubusercontent.com/20731612/164913664-6e417a90-fbc3-4f3f-915e-ae817149ebc7.png)

**Comment by PichotM** [comment]
Fixed by using the latest version of CW (38 is broken)
