### ISSUE TITLE
No asset of type 'Drawable.Bound.Composite.Fragment.Drawable.Dictionary' found! error

### ISSUE THREAD

**Issue by falcon56321** [Skylumz/Sollumz#375]
Hello, my problem is that when I click the auto-create button in the Archetype section, it gives the error in the photo. can you please help

![Adsız](https://user-images.githubusercontent.com/34168507/184269330-3b6c1904-d1b0-4ed6-a2df-7b27234de3ca.png)

**Comment by theM4RI0** [comment]
Firstly, github is for issues, not help, so please, use discord "help" channels to get help.
Second, you need to show your hierarchy, because that error not gonna help a lot, but i can tell you straight, that you didn't create Drawable, but i can be wrong, because there is no much information that can be helpful....

**Comment by falcon56321** [comment]
> Firstly, github is for issues, not help, so please, use discord "help" channels to get help. Second, you need to show your hierarchy, because that error not gonna help a lot, but i can tell you straight, that you didn't create Drawable, but i can be wrong, because there is no much information that can be helpful....

I'm sorry I did not know. Thank you very much for your reply.
