### ISSUE TITLE
can´t export minimap models

### ISSUE THREAD

**Issue by rollschuh2282** [Skylumz/Sollumz#457]
wanted to modify the games minimap for a project and encountered this issue

Steps to Repro:
1. Export one of the minimap .ydd files to xml
2. open blender and import the xml
3. try to export without any changes

instead of exporting, it just gives a error
![bug](https://user-images.githubusercontent.com/53496587/202584222-cf9c9c86-6b20-4569-b042-fcc79365b23f.png)

**Comment by Hancapo** [comment]
Fixed in my fork `SollumzX Reloaded` in [d97b812](https://github.com/Hancapo/SollumzX-Reloaded/commit/d97b812cc751ca4589d260802ed6eb77fc5cb749)  commit but I haven't test it, test it if you want and don't forget to rename the `Drawable Models`, otherwise your YDD will be exported with just one `Drawable`

**Comment by CFox04** [comment]
Fixed in #520
