### ISSUE TITLE
Imported animations incorrect rotation

### ISSUE THREAD

**Issue by MoogieOuttaMyDepth** [Skylumz/Sollumz#458]
I'm following [this guide](https://github.com/Skylumz/Sollumz/wiki/YCD-%7C-Import-&-Edit-&-Export) to a T except importing the Boar animal instead.

I import "creatures@boar@move.ycd.xml" with all tickboxes unchecked and the "head_000_r" armature selected. Then I select a clip, for example "canter", and click "Apply clip to NLA" as instructed.

At this point, the boar model becomes rotated 90 degrees on both the Z and Y axis. What's more, the clip shows the model moving in the wrong direction (positive Y), while animating as if to run towards the positive X direction.

Here's how that looks: https://imgur.com/a/Fo7pxEJ

(Note the darker model you see facing forward is the low LOD. The high LOD initially faced this direction before the clip was applied.)

Blender 3.2.2
CodeWalker 30 dev44 (Sollumz repository linked the only binary of CodeWalker I could find, so I'm aware this may be outdated)

**Comment by PiMoNFeeD** [comment]
can confirm that root motion direction is a problem, I've downloaded codewalker and sollumz for the first time yesterday solely for the purpose of researching animations, and no matter what animations I import, root bone is always rotated incorrectly but for me its not by 90 degrees, its some other unknown number

since cutscene preview in codewalker looks correct (and I so far I've been using cutscene animations only), I am assuming this is a sollumz's problem instead

**Comment by alexguirre** [comment]
This has been fixed in the WIP animation support rework (#709).
