### ISSUE TITLE
Feature suggestion : Favorite slot in vertex paint

### ISSUE THREAD

**Issue by Minibull3** [Skylumz/Sollumz#562]
Hi !

What do you think about add some "favorites" slots to the sollumz vertex paint ?
The idea is to have the ability to save our favorite vertex color (to avoid to save the hex in a external file like .txt and copy/paste it in the sollumz vertex painter).
Maybe 4 or 6 slots ?
Feel free to ping me on sollumz discord if needed :)

**Comment by CuppaT-student** [comment]
So I've done a quick mock-up on a function to do this, I can expand on it if its likely to be added? [https://i.imgur.com/h6ns7Q0.gif](url)

**Comment by CuppaT-student** [comment]
updated and optimized version preview - https://i.imgur.com/q42E9Uy.gif

**Comment by coltfox** [comment]
I may be actually moving some commonly unused features to a separate plugin containing additional tools for Sollumz. The vertex painter isn't used by many people and I'm sure there are other tools that are the same. I'd like to keep Sollumz minimal. Also, with a separate plugin, we can be more liberal about adding tools to it since we don't have to worry about it bloating the main plugin.

**Comment by coltfox** [comment]
Implemented for now in 39cbadd84c8ad4dff72b85863ee23e2e2c374351
