### ISSUE TITLE
Auto update bbMin, bbMax when exporting. Add Collection/Grouping feature for grouping Entities in YTYP

### ISSUE THREAD

**Issue by juliH05** [Skylumz/Sollumz#600]
bbMin and bbMax is currently calculated when creating the archetype for the obj. But when you modify the objekt after you created the archetype it doesnt update the new bbMin and bbMax, you have to recreate the archetype for it to be updated. It would be nice if it would do that automatically.

My secound point is, that it gets messy very fast, if you add a lot of Entities in your YTYP. It would be nice to have a Grouping/Collection feature to clean up your YTYP

**Comment by ultrahacx** [comment]
- bb's are calculated on export and not when YTYP is created. You must have messed something else in order to get incorrect bb's
- I don't think "grouping" entities in YTYP is a nice idea. Use entitysets if you have a lot of entities and have trouble sorting them. Current Archetype UI provides sufficient filtering such as search/sort of entities via names. Grouping then entities would only complicate both the user experience and the code without considerable amount of benifit to users
