### ISSUE TITLE
Embedded Collisions

### ISSUE THREAD

**Issue by vmen007** [Skylumz/Sollumz#684]
With the latest build, after exporting a YDR file with embedded collisions, I encounter two additional files along with it.
I tested it with an older build and didn't encounter these issues.
YDR files still export with the embedded collisions.

![Screenshot 2023-07-18 000546](https://github.com/Skylumz/Sollumz/assets/113604304/4cb5951e-b90c-4f54-8100-93e02ff52b98)

**Comment by P-lauski** [comment]
@vmen007 I also noticed this, and the same occurs with exporting .YDD too, you will get the .YDD and a .YDR as well. What I found is instead of Selecting your hierarchy, you just left click once on your Parent(s) to select it and then export, it will then export like normal without generating those extra files.

**Comment by vmen007** [comment]
@P-lauski easy fix thanks for that

**Comment by coltfox** [comment]
Doesn't appear to be an issue on yft branch. As @Kc2693 said it may be an issue with using a blend file from an old version. Make sure your sollum types are set correctly. If the sollum types got messed up after updating, use the "Fix Hierarchy" debug tool.
