### ISSUE TITLE
Incorrect rotation when importing YMAPS

### ISSUE THREAD

**Issue by vmen007** [Skylumz/Sollumz#704]
When importing default GTA ymaps with default drawables, some objects appear to have incorrect rotation when using Blender 3.6.1 and Solllumz 2.0. I tested this problem with an older version of Solllumz from the main branch 1.0 before it was merged with the yft version, and there were no issues with the import.

https://youtu.be/8DZSDG8MLLk

**Comment by alexguirre** [comment]
This issue seems to have been introduced when merging the main branch into the yft branch: https://github.com/Skylumz/Sollumz/commit/d8aee5ff8d55258535ec14a4be428b471899e07e#diff-8a664933c5aed811f5abb2b837a09bf4b533dc4a066c50605634d56ea747d899R262-R268

It didn't correctly merge PR https://github.com/Skylumz/Sollumz/pull/682, ending up with a duplicated `entity_to_obj` call.
