### ISSUE TITLE
Cannot create water on sollumz 2.2

### ISSUE THREAD

**Issue by manzarek123** [Skylumz/Sollumz#802]
Steps:
1. Create plane
2. Convert plane to drawable with embeded collision
3. Add water fountain shader on model
4. Add Water collision material and water surface flags on col
5. Export
6. Import in codewalker, it is invisible

When adding `<Colour0 />` here:

```
<Layout type="GTAV1">
  <Position />
  <Normal />
  <Colour0 />
  <TexCoord0 />
</Layout>
```

it fixes the issue

**Comment by ook3D** [comment]
good find, also really great that you provided steps to reproduce 👍

**Comment by alexguirre** [comment]
The issue seems to be the Normals, they shouldn't be exported with this shader. Only Position and TexCoord0 are required. When you remove the normals, it shows up fine in CW.

Note, the model still works fine in-game as exported by Sollumz. The game handles additional data in vertices better than CW.

![Original Export](https://github.com/Skylumz/Sollumz/assets/12873137/0b6398e2-2a78-40ec-ae20-24cb3f191886)
![Normals Removed](https://github.com/Skylumz/Sollumz/assets/12873137/b79da73b-f467-4c7c-b4d9-d551137ae35b)
