### ISSUE TITLE
YDR Import infinitely hanging with specific vanilla assets

### ISSUE THREAD

**Issue by ook3D** [Skylumz/Sollumz#862]
for some reason Sollumz refuses to load this drawable 'vw_prop_casino_art_miniature_09c'

**Comment by ook3D** [comment]
attempted to debug this to find where its catching with this decorator,

`def debug_log_decorator(func):
    @functools.wraps(func)
    def wrapper_debug(*args, **kwargs):
        args_repr = [repr(a) for a in args]
        kwargs_repr = [f"{k}={v!r}" for k, v in kwargs.items()]
        signature = ", ".join(args_repr + kwargs_repr)
        print(f"Calling {func.__name__}({signature})")
        result = func(*args, **kwargs)
        print(f"{func.__name__!r} returned {result!r}")
        return result
    return wrapper_debug`
    
[ydr_import_debug_log.txt](https://github.com/Skylumz/Sollumz/files/14291919/ydr_import_debug_log.txt)

**Comment by alexguirre** [comment]
Seems to be the same issue as #737. Blender gets stuck in the code in-between `mesh.from_pydata()` and `mesh.validate()` because the mesh topology is considered invalid by Blender (possibly a degenerate triangle like in #737). In these cases, Blender is allowed to crash or have unexpected behaviour and addons are expected to call `Mesh.validate()`.

The problem is that `validate()` doesn't provide what changes it made to the mesh. So, if called after `from_pydata()`, our normals, UVs and color attributes arrays would end up out-of-sync with the vertices/indices in the mesh. This validation does slightly change lots of vanilla meshes afaik, so it is not acceptable to move `validate()` to after `from_pydata()`. Might need to implement our own custom validation function that modifies all mesh data at the same time.

https://github.com/Skylumz/Sollumz/blob/27bd681db8e1b6e891a14712dbcda2a496765376/ydr/mesh_builder.py#L39-L57

**Comment by alexguirre** [comment]
Confirmed it is the same issue with degenerate triangles as the previous issue. If you remove the indices `3030 3028 3028` from the geometry XML, it imports fine.
![image](https://github.com/Skylumz/Sollumz/assets/12873137/e02d881a-0fb7-4bea-9eb0-a2f7480deb25)

**Comment by alexguirre** [comment]
In the meantime, this script can be used to fix these assets. It will print the invalid triangles and remove them from the XML. It can be run from Blender's scripting tab, just change the file paths.
```py
import xml.etree.ElementTree as ET
import numpy as np

xml = ET.parse("C:\\path\\to\\your\\model.ydr.xml")

for i, indices_elem in enumerate(xml.iterfind(".//IndexBuffer/Data")):
    indices_str = indices_elem.text
    indices_str = " ".join(indices_str.split())
    indices = np.fromstring(indices_str, dtype=int, sep=" ")
    indices = indices.reshape((-1, 3))
    invalid_indices_mask = (indices[:,0] == indices[:,1]) | (indices[:,0] == indices[:,2]) | (indices[:,1] == indices[:,2])
    r = indices[invalid_indices_mask]
    if len(r) > 0:
        print(f"IndexBuffer #{i + 1}")
        print(r)
        indices_elem.text = " ".join(map(str, indices[~invalid_indices_mask].reshape((-1,))))

xml.write("C:\\path\\to\\your\\model_fixed.ydr.xml")
```
